name:                smile
version:             0.1.0.0
github:              ejconlon/smile
license:             MIT
author:              Eric Conlon
maintainer:          ejconlon@gmail.com
copyright:           2019 Eric Conlon

extra-source-files:
- README.md

description: A very opinionated application framework on top of RIO.

dependencies:
- base >= 4.11
- containers
- ekg
- ekg-core
- ekg-statsd
- lens
- mtl
- rio
- template-haskell

default-extensions:
  - ConstraintKinds
  - DeriveFunctor
  - DeriveFoldable
  - DeriveGeneric
  - DeriveTraversable
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - NoImplicitPrelude
  - OverloadedStrings
  - Rank2Types
  - TemplateHaskell

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -fno-warn-unused-top-binds

library:
  source-dirs: src

executables:
  smile-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options: -threaded -rtsopts "-with-rtsopts=-N -T"
    dependencies:
    - smile

tests:
  smile-test:
    main:                Tasty.hs
    source-dirs:         test
    ghc-options: -threaded -rtsopts "-with-rtsopts=-N -T"
    dependencies:
    - smile
    - tasty
    - tasty-discover
    - tasty-hunit